version: '3.7'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
  app:
    build: .
    environment:
      CONNECTION_STRING: 'postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}'
    depends_on:
      - db
    ports:
      - ${APP_PORT}:${APP_PORT}
